FROM python:3.9

WORKDIR  /fastapo_lms

COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# COPY ./app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]