"""moved is active to user table

Revision ID: 877558fdebe3
Revises: 4638ea914e5e
Create Date: 2022-12-30 15:01:56.412378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877558fdebe3'
down_revision = '4638ea914e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_active')
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
